### ISSUE TITLE
bug: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request chat/restore failed with m...

### ISSUE THREAD

**Issue by r3drock** [sourcegraph/jetbrains#1625] opened 2024-05-24 09:36 UTC
### Cody Version

5.5.10

### IDE Information

GoLand 2024.1.2
Build #GO-241.17011.92, built on May 23, 2024
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.8.9-1-default
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
  ide.instant.shutdown=false
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=true
Non-Bundled Plugins:
  lechuck.intellij-plugin.task (1.5.0)
  org.ermadan.kafkalytic (0.10.5)
  some.awesome (1.15)
  org.intellij.plugins.hcl (241.17011.8)
  com.jetbrains.space (241.17011.48)
  com.intellij.kubernetes (241.17011.84)
  IdeaVIM (2.11.0)
  com.intellij.ml.llm (241.17011.2)
  com.sourcegraph.jetbrains (5.5.10)
  com.intellij.bigdatatools.core (241.17011.79)
  com.intellij.bigdatatools.kafka (241.14494.158)
  net.ashald.envfile (3.4.2)
Current Desktop: KDE

### Describe the bug

Can't chat with cody

### Expected behavior

Can chat with cody

### Additional context

Stacktrace:
```text
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request chat/restore failed with message: No default chat model found
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at com.sourcegraph.cody.chat.AgentChatSession.submitMessageToAgent$lambda$1(AgentChatSession.kt:109)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invokeSuspend(CodyAgentService.kt:185)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invoke(CodyAgentService.kt)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invoke(CodyAgentService.kt)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.coWithAgent(CodyAgentService.kt:241)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1.invokeSuspend(CodyAgentService.kt:190)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$2(CodyAgentService.kt:182)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request chat/restore failed with message: No default chat model found
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more

```
Additional info: ```org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request chat/restore failed with message: No default chat model found```

**Comment by odisseus** [comment] 2024-05-29 07:22
Duplicate of #1498.

**Closed as not planned** 2024-06-03 11:51 UTC
Labels: bug, Hide from cycles
