### ISSUE TITLE
bug: Text Input Box Invisible in IntelliJ Light and High Contrast Themes

### ISSUE THREAD

**Issue by LaManoServida** [sourcegraph/jetbrains#1881] opened 2024-07-04 14:06 UTC
### IDE Information

PyCharm 2024.1.4 (Community Edition)
Build #PC-241.18034.82, built on June 24, 2024
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-41-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0.12)
Current Desktop: ubuntu:GNOME

### Bug Description

**Description:**
In the Cody chat interface, the text input box where users type their messages becomes invisible when using the Light and High Contrast themes. This invisibility impacts usability as users cannot easily locate where to enter their text.

**Expected Behavior:**
The text input box should be clearly visible and distinguishable from the background, regardless of the IDE theme being used.

**Actual Behavior:**
The text input box is not visible, blending completely with the background when using Light or High Contrast themes.

### Additional context

![Captura desde 2024-07-04 15-58-29](https://github.com/sourcegraph/jetbrains/assets/26513228/e9b6f363-e021-4cfc-8185-e6f5c42fcd36)

**Comment by mkondratek** [comment] 2024-07-08 10:20
Hi @LaManoServida 👋 thank you for your report and sorry for the inconvenience 🙇‍♂️ I kindly ask you for some patience 
 
---

I quickly reviewed the problem. I am able to reproduce it. The problem is that in our design in both light and dark theme the text are colour is only slightly darker/brighter from the background and there is no border. In contract theme the colours are the same. I was not able to quickly fix it.

We probably should identify the contract theme and use a border with it. Somewhat hackish but we could try to add a border with the background colour (invisible in the light/dark theme but maybe visible in the contrast theme). Also, we probably should decide on webviews first.

**Comment by kalanchan** [comment] 2024-09-16 18:57
@LaManoServida we just upgraded to a new UI, please give it a try :) going to close this, if this is still an issue feel free to re-open.

**Closed as completed by kalanchan** 2024-09-16 18:57 UTC
Labels: bug

**Comment by LaManoServida** [comment] 2024-09-17 17:13
Yes, now it is visible. Thank you.
