### ISSUE TITLE
bug: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request chat/new failed with messa...

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/jetbrains#1498] opened 2024-05-14 03:09 UTC
### Cody Version

5.5.9

### IDE Information

RustRover 2024.1 EAP
Build #RR-241.15989.180, built on May 7, 2024
Licensed to RustRover EAP User
Expiration date: July 6, 2024
Runtime version: 17.0.10+1-b1207.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4050M
Cores: 32
Registry:
  ide.experimental.ui=true
  llm.ai.assistant.toolwindow.activation.on.start=false
  org.toml.json.schema=false
  terminal.new.ui.show.promotion=false
  transferSettings.vscode.onlyCargoToml=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (5.5.9)

### Describe the bug

Logged into sg04 w/ usertesting01 account, credentials in 1pass. Chatted to Cody.

### Expected behavior

Chats should work.

### Additional context

Stacktrace:
```text
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request chat/new failed with message: No chat model found in server-provided config
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at com.sourcegraph.cody.chat.AgentChatSession.submitMessageToAgent$lambda$1(AgentChatSession.kt:109)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invokeSuspend(CodyAgentService.kt:185)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invoke(CodyAgentService.kt)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invoke(CodyAgentService.kt)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.coWithAgent(CodyAgentService.kt:241)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1.invokeSuspend(CodyAgentService.kt:190)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$2(CodyAgentService.kt:182)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request chat/new failed with message: No chat model found in server-provided config
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more

```
Additional info: ```org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request chat/new failed with message: No chat model found in server-provided config```

**Comment by pkukielka** [comment] 2024-05-15 15:54
Unfortunately I cannot reproduce it even on sg04.
@dominiccooney has it happened once or was it more reproducible?
Can you still reproduce it?

**Comment by mark5280** [comment] 2024-05-15 19:36
I'm still seeing this issue in version 5.5.10 of the Jetbrains IntelliJ plugin.

**Comment by pkukielka** [comment] 2024-05-16 07:35
@mark5280 could you send me your IntelliJ logfile? Maybe there will be some additional clues in there. 
https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

Also, is the problem manifesting only sometimes, or is it constantly failing with that error?
When does it appear, when you try to open a new chat, sent a message, or in some other scenario?

**Comment by pkukielka** [comment] 2024-05-16 08:51
Looks like the same problem we have seen here:
https://github.com/sourcegraph/cody/issues/3663
which was fixed by @abeatrix : https://github.com/sourcegraph/cody/pull/3650

`5.5.9` already contains that fix, so perhaps it's a regression?
@abeatrix the bit of code which is failing there has not changed in JetBrain for at least a couple of weeks, do you see any way it could still be failing on the VSCode side?

**Comment by dominiccooney** [comment] 2024-05-16 13:56
@pkukielka this is the observation I mentioned in Slack, https://github.com/sourcegraph/jetbrains/issues/1483#issuecomment-2106582627 , but reading sourcegraph/cody#3650 I think my observation is unrelated.

It sounds like a timing issue.

We could simply make chat block on the model list, with a timeout so we can add Telemetry/retry/user message when it is slow.

**Comment by mark5280** [comment] 2024-05-16 14:56
It looks like an auth token issue in my case.  Here is some of the IntelliJ logging that points this out. If I go through the Manage Account in the Cody plugin, I'm successfully logged into my Sourcegraph account. Is there a means to manually update my auth token for Cody from within IntelliJ?

```
2024-05-16 08:53:42,143 [   5100]   INFO - #com.sourcegraph.cody.agent.CodyAgent - extracting Node binary to /var/folders/yw/n2y6dzsn4_76wv46c9tsvdfr0000gp/T/cody-agent3765952793999496224
2024-05-16 08:53:42,181 [   5138]   INFO - #com.sourcegraph.cody.agent.CodyAgent - starting Cody agent /var/folders/yw/n2y6dzsn4_76wv46c9tsvdfr0000gp/T/cody-agent3765952793999496224 /Users/mferguso/Library/Application Support/JetBrains/IntelliJIdea2024.1/plugins/Sourcegraph/agent/index.js

2024-05-16 08:53:44,502 [   7459]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-05-16 08:53:44,502 [   7459]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ AuthProvider:init: No token found in secretStorage
2024-05-16 08:53:44,503 [   7460]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ AuthProvider:init:lastEndpoint: https://sourcegraph.com/
2024-05-16 08:53:44,656 [   7613]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ featureflag: refreshed
2024-05-16 08:53:44,659 [   7616]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ featureflag: refreshed
2024-05-16 08:53:44,680 [   7637]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ContextFiltersProvider: setContextFilters 
2024-05-16 08:53:44,682 [   7639]   WARN - org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint - Unexpected params '[null]' for 'public void com.sourcegraph.cody.agent.CodyAgentClient.ignoreDidChange()' is ignored
2024-05-16 08:53:44,682 [   7639]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatManager:constructor: init no local embeddings
2024-05-16 08:53:44,682 [   7639]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatPanelsManager:constructor: init
2024-05-16 08:53:44,682 [   7639]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SymfRunner: unsafeEnsureIndex file:///Users/mferguso/Dev/ttat/
2024-05-16 08:53:44,682 [   7639]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CommandsController:init: watchers created
2024-05-16 08:53:44,682 [   7639]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ telemetry-v2: recordEvent: cody.signInNotification/shown 
2024-05-16 08:53:44,682 [   7639]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - window.showErrorMessage: Sign in to Cody to get started
2024-05-16 08:53:44,682 [   7639]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-05-16 08:53:44,682 [   7639]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:notSignedIn: You are not signed in.
2024-05-16 08:53:44,735 [   7692]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ GraphQLTelemetryExporter: evaluated export mode: 5.2.5+
2024-05-16 08:53:44,832 [   7789]   WARN - org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint - Unexpected params '[null]' for 'public void com.sourcegraph.cody.agent.CodyAgentClient.remoteRepoDidChange()' is ignored
2024-05-16 08:53:44,833 [   7790]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:notSignedIn: You are not signed in.
2024-05-16 08:53:44,833 [   7790]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ Cody:publishConfig: configForWebview 
2024-05-16 08:53:44,833 [   7790]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ContextProvider:onConfigurationChange: using codebase 
2024-05-16 08:53:44,833 [   7790]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ logEvent: CodyJetBrainsPlugin:Auth:failed 
2024-05-16 08:53:44,833 [   7790]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ telemetry-v2: recordEvent: cody.auth/failed 
2024-05-16 08:53:44,834 [   7791]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:notSignedIn: You are not signed in.
2024-05-16 08:53:44,902 [   7859]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ContextFiltersProvider: fetchContextFilters 
2024-05-16 08:53:44,909 [   7866]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ContextFiltersProvider: fetchContextFilters 
2024-05-16 08:53:44,910 [   7867]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ContextProvider:onConfigurationChange: using codebase 
2024-05-16 08:53:44,947 [   7904]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ GraphQLTelemetryExporter: telemetry: failed to evaluate server version: Error: accessing Sourcegraph GraphQL API: Error: HTTP status code 401: Invalid access token.
 (https://sourcegraph.com/.api/graphql?SiteProductVersion)
2024-05-16 08:53:44,953 [   7910]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ featureflag: refreshed
2024-05-16 08:53:44,953 [   7910]   WARN - #com.sourcegraph.cody.agent.CodyAgent - Connected to Cody agent cody-agent
2024-05-16 08:53:45,023 [   7980]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ GraphQLTelemetryExporter: Error exporting telemetry events: Error: accessing Sourcegraph GraphQL API: Error: HTTP status code 401: Invalid access token.
 (https://sourcegraph.com/.api/graphql?RecordTelemetryEvents)
2024-05-16 08:53:45,023 [   7980]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ EventLogger: Error logging event Error: accessing Sourcegraph GraphQL API: Error: HTTP status code 401: Invalid access token.
 (https://sourcegraph.com/.api/graphql?LogEventMutation)
2024-05-16 08:53:45,145 [   8102]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ featureflag: refreshed
2024-05-16 08:53:45,146 [   8103]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:notSignedIn: You are not signed in.
2024-05-16 08:53:45,146 [   8103]   WARN - #com.sourcegraph.cody.initialization.EndOfTrialNotificationScheduler - Error while getting currentUserCodySubscription 
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request graphql/getCurrentUserCodySubscription failed with message: accessing Sourcegraph GraphQL API: Error: HTTP status code 401: Invalid access token.
 (https://sourcegraph.com/.api/graphql?CurrentUserCodySubscription)
```

**Comment by mark5280** [comment] 2024-05-16 16:37
Using the logs above, I was able to deduce that my auth token had somehow been invalidated and had to be regenerated.  Through the IntelliJ plugin interface for Cody I took the following steps:
- When the Cody window is opened in IntelliJ click on the gear icon on the top right and select Cody Settings
- Under the Authentication section, select and delete the current auth token
- In that same section, now click Add Account and select Log in to Sourcegraph
- Click Authorize in the browser window that is displayed
- Click OK and restart IntelliJ
- Cody should now work again

**Comment by dominiccooney** [comment] 2024-05-22 00:16
Thank you for the detailed repro steps @mark5280 !

**Comment by odisseus** [comment] 2024-06-05 03:02
I have confirmed that the agent endpoints (chat/new and chat/restore) work incorrectly if the user is not authorised. The VS Code client avoids this problem, because it disables the whole chat panel when the user is not authorised; these requests are therefore not sent at all.

**Comment by user753** [comment] 2024-06-05 10:10
I have the same problem after upgrade to v6.0.3 
I tried to relogin, delete tokens, nothing helps, so I downgraded to v5.5.10 and everything works

**Comment by odisseus** [comment] 2024-06-07 10:35
@user753, are you trying to restore an old chat from the history? Could you please try creating a fresh new chat and check if it works?

**Closed as completed** 2024-06-10 10:14 UTC
Labels: bug, clients/jetbrains

**Comment by user753** [comment] 2024-06-20 18:24
@odisseus No, I just uninstall and install cody 6.0.3 again. I successfully login to cody, but nothing is working no autocomplete no chat. What can I do?
Everything works fine in 5.5.10. You really broke something in 6.0.3

**Comment by pkukielka** [comment] 2024-06-21 10:00
@user753 Can you please create a new ticket with attached idea.log? We will be happy to look into it but we need more data.

**Comment by user753** [comment] 2024-06-21 10:18
@pkukielka I look at idea.log The problem is cody don't use proxy settings correctly somehow. I remove my proxy from Idea settings and it start working. My proxy works fine.
```
2024-06-21 13:07:18,074 [  15734]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ GraphQLTelemetryExporter: telemetry: failed to evaluate server version: Error: accessing Sourcegraph GraphQL API: Error: HTTP status code 407: <html><head><title>407 Proxy Authentication Required</title></head>

<body><h2>407 Proxy Authentication Required</h2><h3>Access to requested resource disallowed by administrator or you need valid username/password to use this resource</h3></body></html>
```
