### ISSUE TITLE
JetBrains: "explain selected code" does not correctly reflect the selection

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/jetbrains#69] opened 2023-10-26 06:49 UTC
Reported in https://sourcegraph.slack.com/archives/C059N5FRYG3/p1698264046869589

Steps to reproduce:

- See https://www.loom.com/share/defdeb5f1b054a5ab3a8003b33cd4396?sid=56a3d868-363c-4ff1-b442-782363e3804c
- Write a function A with 5 lines code of code
- Select the code in function B below A that also has 5 lines of code
- Trigger recipe "explain selected code"
- Cody explains function A instead of function B

**Comment by exigow** [comment] 2023-11-02 13:35
@olafurpg, I was able to replicate the issue once by following the steps outlined, but I'm having difficulties trying to do so again. Could you please re-upload the clip using a platform other than Loom? The file appears to be restricted, and I've requested access, but I just noticed that the owner is on vacation.

**Comment by olafurpg** [comment] 2023-11-02 14:06
@exigow I just sent you a download of the Loom

**Comment by exigow** [comment] 2023-11-06 09:23
![Image](https://github.com/sourcegraph/jetbrains/assets/5013708/67fd1fa6-ea68-4aff-92b7-04f9889b76db)
![Image](https://github.com/sourcegraph/jetbrains/assets/5013708/3dbbd90e-2aee-4e41-a35a-c8b0629985fc)

I have bad luck with reproducing this error. I tried to simulate the steps from instructions and video ([BoxOfficeMoviesAdapter.java](https://github.com/codepath/android-rottentomatoes-demo/blob/1d7aed03cd07f9c95ef77c65892717119ccea648/src/com/codepath/example/rottentomatoes/BoxOfficeMoviesAdapter.java)) in multiple ways and during daily tasks with hope that my current IDE state may invoke this, but the explanation was always correct.

I think that the number of lines may not fully affect this error because we have a case where the functions have different lengths.

I'm thinking that I'm missing something and there are some specific steps that need to be taken **before** generating the function / clicking "explain". @ajaynz and @@olafurpg, can you share a broader context and description of the environment in which this occurs? Maybe it's related to specific plugin version or project setup?

**Comment by ajaynz** [comment] 2023-11-06 09:45
Just did a screen share with Jakub, I could reproduce it consistently as per original report.
The Github project I was using is https://github.com/codepath/android-rottentomatoes-demo

**Comment by exigow** [comment] 2023-11-06 14:06
@ajaynz, may I kindly request your help in reproducing this issue with logging enabled and sharing the resulting logs with me?

In short, it would go like this:

1. You have to set system variable with enabled logs, for example: `cody-agent.trace-path=/my/path/logs.json` and restart IDE.
2. Perform a test that will replicate this error and note the exact time when the "explain" is invoked and it's not working correctly - this will allow me to search the logs more easily.
3. Shut down the IDE (preferably right after the test to reduce amount of unnecessary logs) and share that file.

That would be very helpful. Please note that this log may contain your API key which it would be good if you could anonymize/remove before sending. To be sure, you can send me this file in direct message.

**Comment by exigow** [comment] 2023-11-08 16:50
At the end of the day, I've managed to identify two issues and started to working on a fix. 

Here is my research so far:

## 1. The generated code returns excessive or missing closing braces

* It appears that this error is partly caused by the incorrect number of braces generated through multiline completion.
* Upon reviewing the attached video, it's evident that the generated bubblesort algorithm has **one extra closing brace**.
* This implies that the last line of implementation effectively closes the code for the entire class (see: line 32).
* Consequently, everything below line 32 constitutes a separate block.
* Fun fact: the agent sometimes is immune to this and other times not (the behavior is very non-deterministic - I suspect there might be an instruction in the prompt to handle this scenario).
* Asking the chat to explicitly count all the open and closed curly braces returns an incorrect answer (8 open and 8 closing).
* The content contained in textDocument/didChange still includes the extra brace.

## 2. (this is huge :lady_beetle:) Selection line/character sent do agent is incorrect when code is partially collapsed in IDE

* It seems that the selection position is calculated based on what we see in IntelliJ, not the actual content of the file.
* It is easy to reproduce: If we collapse the entire code using Ctrl + Shift + Minus, we end up sending a completely random cursor position.
* The selection only works correctly if we fully expand the code using Ctrl + Shift + Plus.
* This error essentially always occurs because IntelliJ **collapses imports by default**, so the line is always shifted by the offset of the number of import lines.
* This is clearly the reason why @ajaynz received an explanation of the bubblesort algorithm - selection was pointing to different method.

Note that the agent is functioning correctly and the issue is only on JetBrains plugin side.

**Comment by mkondratek** [comment] 2023-11-09 10:04
And I can certainly confirm the second - the issue with collapsed blocks. I saw that while I was investigating https://github.com/sourcegraph/sourcegraph/issues/58160.

**Closed as completed** 2023-11-09 13:53 UTC
