### ISSUE TITLE
JetBrains: "Document Code" and "Generate Unit Tests" commands stopped working when switching between projects.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1617] opened 2024-05-23 19:39 UTC
### Cody Version

v5.5.12-nightly

### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  de.sgalinski.typoscript.enterprise.plugin.id (2.8.0)
  org.jetbrains.plugins.hocon (2023.1.0)
  PythonCore (233.14475.9)
  com.soywiz.korge.korge-intellij-plugin (4.0.4)
  com.sourcegraph.jetbrains (5.5.12-nightly)
Kotlin: 233.14475.28-IJ

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free user
3. Open any source code file from Project-A 
4. Go to Commands and run "Document Code" command
5. Switch to Project-B and open any source code file
6. Go to Commands and run "Document Code" command
7. Repeat above steps-3 to step-6 

### Observed behavior:
"Document Code" and "Generate Unit Tests" commands stopped working

### Expected behavior

"Document Code" and "Generate Unit Tests" commands should continue working just like remaining commands i.e. Explain Code

### Additional context

**Attaching idea logs** 
[idea.log](https://github.com/sourcegraph/jetbrains/files/15421826/idea.log)

**Video link:**
https://drive.google.com/file/d/1nmkPcQH1NwLQkwNCq7FV378QXsiLlOKm/view?usp=drive_link

**Comment by mkondratek** [comment] 2024-06-03 22:30
I retried it a few times and I cannot reproduce it now. We made a great progress in terms of Inline Edit stability (fixup session handling, document sync, etc). closing

**Closed as completed by mkondratek** 2024-06-03 22:30 UTC
Labels: bug, fibilabs-qa, fibilabs-qa-p1, clients/jetbrains
