### ISSUE TITLE
JetBrains: Continuous loading on clicking Apply button after sending request using same source code file

### ISSUE THREAD

**Issue by RajatNagoria** [sourcegraph/jetbrains#2103] opened 2024-08-22 20:38 UTC
### IDE Information

IntellJ IDEA 2024.1.4 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
com.sourcegraph.jetbrains (6.0.31)

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Enterprise user
3. Open Chat snippet and search for anything > Insert the search code to source code file
4. Now start New chat > Make sure current repository and current source file is shown
5. Send the request using that > Make sure same code is given as response
6. Now click on 'Apply button'

### Observed Behavior:
Continuous loading on clicking Apply button after sending request using same source code file

### Expected behavior:
Apply button should work properly and no continuous loading should be shown

### Additional context

**Video link:** https://drive.google.com/file/d/1vvMIEM-WWYVWqIWOZ-Dmlqxwh9DHGQ0R/view

**Comment by mkondratek** [comment] 2024-08-27 11:41
I tried this scenario. It works for me. Possibly it has been fixed already. IMO we can close this one.

**Comment by RajatNagoria** [comment] 2024-08-27 14:35
Looks Like issue is fixed, hence closing

**Comment by RajatNagoria** [comment] 2024-08-27 14:36
Looks Like issue is fixed, hence closing

**Comment by RajatNagoria** [comment] 2024-08-27 19:55
Reopening as issue is again repro in 6.0.35 Nightly

**Comment by mkondratek** [comment] 2024-08-28 16:33
I cannot reproduce it. Are the steps up to date? I admit that I am working on macOS while your example shows Windows. I am going to try it too.

**Comment by mkondratek** [comment] 2024-08-28 18:11
I manage to reproduce some issue (not sure if that exactly what we see in this report). The problem seems to be related to **the windows env and the space character in the file name**. I would consider this one as a medium prio at most since the conditions are extraordinary. I am going to look into it.

**Closed as completed** 2024-12-02 22:27 UTC
Labels: bug, fibilabs-qa, fibilabs-qa-p1, repo/jetbrains
