### ISSUE TITLE
JetBrains: Deleted test file appear again when editing original source code file. 

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1901] opened 2024-07-10 19:05 UTC
### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  idea.plugin.protoeditor (233.13135.65)
  DevKit (233.14015.152)
  gherkin (233.11799.165)
  cucumber-java (233.11799.196)
  PythonCore (233.14015.106)
  com.sourcegraph.jetbrains (6.0.14-nightly)
Kotlin: 233.14015.106-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Open any source code file and right click to open context menu
4. Choose "Cody > Generate Unit Tests" and let Cody finish writing the unit test file
5. Delete the unit file and edit the original source code file

### Observed behavior:
Deleted unit test file reappear.

### Expected behavior:
Deleted unit test file should not appear again. 

### Additional context

**Video link:**

https://drive.google.com/file/d/1mf1VE1PEJP45OhvTzABFWXjEpewT3F9N/view?usp=drive_link

**Comment by mkondratek** [comment] 2024-07-11 08:11
This is a duplicate of https://linear.app/sourcegraph/issue/CODY-2004/bug-cody-recreates-the-file-that-was-created-by-generate-unit-tests

**Closed as completed by mkondratek** 2024-07-11 08:11 UTC
Labels: bug, fibilabs-qa, fibilabs-qa-p1
