### ISSUE TITLE
bug: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: No default chat model found

### ISSUE THREAD

**Issue by ernestoBizDirect** [sourcegraph/jetbrains#1763] opened 2024-06-09 02:46 UTC
### IDE Information

PyCharm 2023.3 (Professional Edition)
Build #PY-233.11799.259, built on December 3, 2023
Licensed to gurgles tumbles
You have a perpetual fallback license for this version.
Subscription is active until September 14, 2026.
Runtime version: 17.0.9+7-b1087.7 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  atom-one (1.5.1)
  com.supermaven.intellij (1.25)
  com.intellij.plugins.vscodekeymap (233.11799.188)
  app.aicommit.plugin (3.0.8)
  net.firebits.odoo (1.2.1)
  at.wtioit.intellij.plugins.odoo (0.6.11)
  dev.ngocta.pycharm-odoo (2024.4.0.233)
  com.sourcegraph.jetbrains (6.0.4-nightly)
  cn.yiiguxing.plugin.translate (3.6.1)

### Bug Description

There must be some way to reload the models, sometimes the IDE loads and I have a bad Internet connection and therefore the models do not load, then even though the connection returns it is no longer possible to reload, I have to close the IDE and restart it to open. On other occasions, only the free Claude Sonnet model is loaded, even though he recognizes that my subscription is the Pro, in the same way in that case I must restart the IDE

### Additional context

Stacktrace:

```text
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: No default chat model found
 
Error: No default chat model found
    at /Users/developer/Library/Application Support/JetBrains/PyCharm2023.3/plugins/Sourcegraph/agent/index.js:112466:19
 at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
 at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
 at com.sourcegraph.cody.chat.AgentChatSession.submitMessageToAgent$lambda$0(AgentChatSession.kt:121)
 at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invokeSuspend(CodyAgentService.kt:260)
 at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invoke(CodyAgentService.kt)
 at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invoke(CodyAgentService.kt)
 at com.sourcegraph.cody.agent.CodyAgentService$Companion.coWithAgent(CodyAgentService.kt:317)
 at com.sourcegraph.cody.agent.CodyAgentService$Companion.access$coWithAgent(CodyAgentService.kt:227)
 at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1.invokeSuspend(CodyAgentService.kt:266)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
 at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
 at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
 at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
 at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
 at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
 at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$2(CodyAgentService.kt:257)
 at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
 at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
 at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: No default chat model found
 
Error: No default chat model found
    at /Users/developer/Library/Application Support/JetBrains/PyCharm2023.3/plugins/Sourcegraph/agent/index.js:112466:19
 at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
 at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
 at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
 at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
 at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 ... 1 more
 
```

Additional info:

```text
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: No default chat model found

Error: No default chat model found
    at /Users/developer/Library/Application Support/JetBrains/PyCharm2023.3/plugins/Sourcegraph/agent/index.js:112466:19
```

**Comment by odisseus** [comment] 2024-06-10 11:33
This issue is related to #1498.

**Comment by mkondratek** [comment] 2024-06-21 11:54
That could be caused by an authorization error (so it will be likely fixed by https://github.com/sourcegraph/jetbrains/pull/1796)

**Comment by mkondratek** [comment] 2024-07-03 21:06
Hello @ernestoBizDirect 👋 it took a while but we did a lot of fixing and improvements. Can you please update the plugin to 6.0.12 and check it? Does it fix our case?

**Comment by ernestoBizDirect** [comment] 2024-07-08 14:39
> Hello @ernestoBizDirect 👋 it took a while but we did a lot of fixing and improvements. Can you please update the plugin to 6.0.12 and check it? Does it fix our case?

Hello @mkondratek , the main problem is that in the version for jetbains there is no button that allows reloading the models, unlike the Visual Studio Code version that when there are connection problems a "Retry" button allows reloading when there are connection problems, which forces me to reload the IDE over and over again until I get lucky. For now and waiting I have migrated to VSCode.
![image](https://github.com/sourcegraph/jetbrains/assets/152932340/9aafa25e-ead2-46c6-bc58-b3454f21a1ec)
![image](https://github.com/sourcegraph/jetbrains/assets/152932340/bdee969f-4a79-4361-8349-9c4459ae2ee1)
![image](https://github.com/sourcegraph/jetbrains/assets/152932340/261304c2-e3d4-4b76-9b82-473d755dcac9)

**Comment by mkondratek** [comment] 2024-07-08 15:41
Thanks for more details. Looks like the model is still not loading correctly... can you see any errors? is it still the same?

(note: speaking of `Retry` - you can try `Command + Shift + A` [Search Everywhere - Actions] and find and run this action: "Restart Cody Agent" - that can resolve some problems)

**Closed as not planned** 2024-11-27 22:33 UTC
Labels: bug, repo/jetbrains
