### ISSUE TITLE
JetBrains: Cody keeps removing and re-adding generated response.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#929] opened 2024-02-29 19:54 UTC
### Installation Information

Plugin version: `5.3.2625-nightly`
IDE version: `PC-233.13763.11`

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains PyCharm editor
2. User is already logged in to Cody with Free/Pro/Enterprise account
3. Open any file and ask Cody "Generate Document"
4. Observe the response

**Observed behavior:**
Cody keeps removing and re-adding generated response and user experience is unpleasant.

### Expected behavior

Generated response should be persisted.

### Additional context (logs, images, etc)

**Video link:**

https://drive.google.com/file/d/1fj7IIX0NgvVEOPjJhY1kzfY-eWuGQgQE/view?usp=drive_link

**Comment by taylorsperry** [comment] 2024-03-05 17:51
Woah, strange! I'm not able to repro this on `5.3.2999-nightly` on MacOS @jay-fibi. Could you check to see if the issue is resolved? Or is it specific to Windows?

**Comment by jay-fibi** [comment] 2024-03-05 18:31
Hi @taylorsperry I am still able to repro this issue with `5.3.2999-nightly` on both Windows and MacOS. Here are the refined steps,
1. Have a `Jetbrains `project cloned to the editor via VCS
2. Switch to another project and wait for some time
3. Switch to `Jetbrains` and open any file quickly and type "Generate Document" command in Cody

**Comment by mkondratek** [comment] 2024-04-15 10:12
@jay-fibi, are you still able to reproduce it? 

We did some improvements to the receiving process after `5.3.2999`. 
I just tried to reproduce it with no success. 

If you could confirm that you too are not able to reproduce it we could close it.

**Comment by jay-fibi** [comment] 2024-04-15 15:09
@mkondratek Feel free to close it. It is not reproducible with 5.5.5 build.

**Closed as completed** 2024-04-17 16:20 UTC
Labels: bug, fibilabs-qa
