### ISSUE TITLE
bug: getaddrinfo ENOTFOUND sourcegraph.com

### ISSUE THREAD

**Issue by zeloras** [sourcegraph/jetbrains#1893] opened 2024-07-08 21:52 UTC
### IDE Information

PyCharm 2024.1.4 (Professional Edition)
Build #PY-241.18034.82, built on June 24, 2024
Licensed to Nikolay Ponich
You have a perpetual fallback license for this version.
Subscription is active until June 21, 2025.
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 3048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  editor.minimap.enabled=true
  terminal.new.ui=true
Non-Bundled Plugins:
  com.github.bric3.excalidraw (0.4.0)
  org.intellij.plugins.hcl (241.17890.8)
  intellij.webp (241.14494.150)
  com.jetbrains.space (241.18034.4)
  e.v.cats-progress-bar (1.2.0)
  IdeaVIM (2.13.1)
  me.lensvol.blackconnect (0.6.2)
  pro.bashsupport (4.2.1.241)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-241)
  com.intellij.ml.llm (241.18034.12)
  com.github.jk1.ytplugin (2024.2.117)
  com.sourcegraph.jetbrains (6.0.13-nightly)
  mobi.hsz.idea.gitignore (4.5.3)
  com.github.copilot (1.5.14.6008)
  ru.adelf.idea.dotenv (2024.1)
  com.intellij.bigdatatools.core (241.18034.62)
  com.intellij.bigdatatools.binary.files (241.14494.158)
  com.intellij.bigdatatools.rfs (241.18034.62)
  com.intellij.bigdatatools.metastore.core (241.14494.158)
  com.intellij.bigdatatools.flink (241.14494.158)

### Bug Description

just use vpn

### Additional context

Stacktrace: ```getaddrinfo ENOTFOUND sourcegraph.com```

**Comment by odisseus** [comment] 2024-07-24 13:38
Looks like your VPN or proxy cannot access `sourcegraph.com` for some reason. Can you try disabling it?

Possibly a duplicate of #1195.

**Comment by arshia93** [comment] 2024-07-24 20:46
I'm also seeing this bug on vs code: Request Failed: getaddrinfo ENOTFOUND sourcegraph.com

**Comment by kalanchan** [comment] 2024-09-16 18:54
going to close this, if this is still an issue feel free to re-open

**Closed as completed by kalanchan** 2024-09-16 18:54 UTC
Labels: bug
