### ISSUE TITLE
bug: java.nio.file.InvalidPathException: Illegal char <"> at index 1: {"sessionId":"1708445392606","projectHash":"49d98b1c (...)

### ISSUE THREAD

**Issue by ceearrashee** [sourcegraph/jetbrains#758] opened 2024-02-20 16:49 UTC
Plugin version: ```5.3.27-nightly```
IDE version: ```GO-233.14475.38```
Stacktrace:
```text
java.nio.file.InvalidPathException: Illegal char <"> at index 1: {"sessionId":"1708445392606","projectHash":"49d98b1c","repository":{"serverPath":{"myHost":"github.com"},"repositoryPath":{"owner":"mouselive","repository":"flutter_mobile"}},"prId":{"id":"PR_kwDOCqdQ_s5mHS5N","number":52},"isDiff":false}
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:177)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.sourcegraph.cody.agent.protocol.TextDocument$Companion.fromPath(TextDocument.kt:18)
	at com.sourcegraph.cody.agent.protocol.TextDocument$Companion.fromPath$default(TextDocument.kt:17)
	at com.sourcegraph.cody.agent.protocol.TextDocument$Companion.fromPath(TextDocument.kt)
	at com.sourcegraph.cody.agent.protocol.TextDocument.fromPath(TextDocument.kt)
	at com.sourcegraph.cody.CodyFileEditorListener.lambda$fileClosed$1(CodyFileEditorListener.java:37)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$0(CodyAgentService.kt:123)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by pkukielka** [comment] 2024-02-28 11:51
Duplicate of https://github.com/sourcegraph/jetbrains/issues/609
Fixed in https://github.com/sourcegraph/jetbrains/pull/897

Fix will be available in a new release in a ~week from now.

**Closed as completed by pkukielka** 2024-02-28 11:51 UTC
