### ISSUE TITLE
JetBrains: User can trigger Cody Autocompletion even after disabling it.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#992] opened 2024-03-06 15:30 UTC
### Installation Information

Plugin version: `5.3.3899-nightly`
IDE version: `IC-233.14475.28`

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody with Free/Pro/Enterprise account
3. Click on Cody icon and click on "Disable Cody Autocomplete" to disable it
4. Paste the following Java code
```
// print Hello World!
System.out.
```
5. Place a cursor at the end of the `System.out.` line
6. Trigger autocompletion with `Alt` + `/`

### Observed behavior:
Cody Autocompletion triggered and complete the line of code.

### Expected behavior

Cody Autocompletion should be disabled.

### Additional context

**Video link:**

https://drive.google.com/file/d/1LvItL1cIGbFNoOPWnEUPRfZHxvvhQ7Cn/view?usp=drive_link

**Comment by dominiccooney** [comment] 2024-05-24 09:18
I can't reproduce this on trunk around 5.5.12; this must have been fixed in the meantime.

**Closed as completed by dominiccooney** 2024-05-24 09:18 UTC
Labels: bug, fibilabs-qa, clients/jetbrains
