### ISSUE TITLE
JetBrains: format indentation in chat UI

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/jetbrains#50] opened 2023-10-23 09:29 UTC
Paste in this code into chat
```

    var updatedEventParameters = eventParameters.deepCopy();
    if (params != null) {
      if (params.contextSummary != null) {
        updatedEventParameters.add("contextSummary", gson.toJsonTree(params.contextSummary));
      }

```

The indentation gets lost when the code is formatted in the chat

![Image](https://github.com/sourcegraph/jetbrains/assets/1408093/86d724a4-89c4-4fe6-8a23-3e6f2b696bda)

My expectation is that the chat message in the UI preserves the original indentation.

**Comment by mkondratek** [comment] 2024-03-12 18:26
I verified back to v5.2.1720. I cannot reproduce it. Closing.

**Closed as completed by mkondratek** 2024-03-12 18:26 UTC
