### ISSUE TITLE
bug: Invalid access token error is missing a proper handling

### ISSUE THREAD

**Issue by jon-humble** [sourcegraph/jetbrains#1035] opened 2024-03-11 13:34 UTC
Plugin version: `5.3.3914`
IDE version: `IC-232.10227.8`
Stacktrace:

```text
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: accessing Sourcegraph GraphQL API: Error: HTTP status code 401: Invalid access token.
 (https://sourcegraph.com/.api/graphql?CurrentUserCodyProEnabled)
 
Error: accessing Sourcegraph GraphQL API: Error: HTTP status code 401: Invalid access token.
 (https://sourcegraph.com/.api/graphql?CurrentUserCodyProEnabled)
    at /snapshot/dist/agent.js
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /snapshot/dist/agent.js
 at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
 at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
 at com.sourcegraph.cody.chat.ui.LLMDropdown.fetchAndUpdateModels$lambda$1(LLMDropdown.kt:49)
 at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$0(CodyAgentService.kt:125)
 at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
 at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: accessing Sourcegraph GraphQL API: Error: HTTP status code 401: Invalid access token.
 (https://sourcegraph.com/.api/graphql?CurrentUserCodyProEnabled)
 
Error: accessing Sourcegraph GraphQL API: Error: HTTP status code 401: Invalid access token.
 (https://sourcegraph.com/.api/graphql?CurrentUserCodyProEnabled)
    at /snapshot/dist/agent.js
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /snapshot/dist/agent.js
 at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
 at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
 at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
 at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
 at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 ... 1 more
 
```

**Comment by mkondratek** [comment] 2024-03-19 08:30
Hello @jon-humble   👋 thanks for the report

I am looking at the other report: https://github.com/sourcegraph/jetbrains/issues/991 - it failed there almost identically but on `CurrentUserCodySubscription`. 

Here `CurrentUserCodyProEnabled` is troublesome.

What bothers me is that we believe the other issue is fixed in `5.3.3914` while this is `5.3.3914` and a very similar issue appears.

@jon-humble, can you try to regenerate the token and retry? does it help? Also, can you provide more specifics steps to reproduce it? Is this issue blocking you 100% in using Cody or just appears sometimes? 

(cc: @pkukielka)

**Comment by mkondratek** [comment] 2024-03-19 09:38
@jon-humble, I looked closer into this issue. It seems that one of the causes can be that the token expired. Our messaging in this area is far from perfect now - sorry about it. Please remove regenerate a new token and retry. 🙏

**Comment by mkondratek** [comment] 2024-03-19 09:54
btw, I just noted we are totally missing the error handling for the autocompletions. I just reviewed my logs and I see lots of:

```
2024-03-19 10:50:57,452 [2840410]   WARN - #c.s.c.a.CodyAgent - Uncaught exception: Error: accessing Sourcegraph GraphQL API: Error: HTTP status code 401: Invalid access token.
2024-03-19 10:50:57,453 [2840411]   WARN - #c.s.c.a.CodyAgent -  (https://sg02.sourcegraphcloud.com/.api/graphql?Repository)
2024-03-19 10:50:57,453 [2840411]   WARN - #c.s.c.a.CodyAgent -     at /snapshot/cody-b66ee05d2f81df0fda5d6c9f1b292696c163c3bc/agent/dist/index.js:28127:20
2024-03-19 10:50:57,453 [2840411]   WARN - #c.s.c.a.CodyAgent -     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-19 10:50:57,453 [2840411]   WARN - #c.s.c.a.CodyAgent -     at async WorkspaceRepoMapper.repoForCodebase (/snapshot/cody-b66ee05d2f81df0fda5d6c9f1b292696c163c3bc/agent/dist/index.js:132966:24)
2024-03-19 10:50:57,453 [2840411]   WARN - #c.s.c.a.CodyAgent -     at async CodebaseStatusProvider._updateCodebase_NoFire (/snapshot/cody-b66ee05d2f81df0fda5d6c9f1b292696c163c3bc/agent/dist/index.js:115043:41)
2024-03-19 10:50:57,453 [2840411]   WARN - #c.s.c.a.CodyAgent -     at async CodebaseStatusProvider.updateStatus (/snapshot/cody-b66ee05d2f81df0fda5d6c9f1b292696c163c3bc/agent/dist/index.js:115025:35)
```

**Closed as completed** 2024-06-03 22:11 UTC
Labels: bug, clients/jetbrains
