### ISSUE TITLE
bug: java.util.concurrent.CompletionException: java.lang.Exception: Failed to start Cody agent

### ISSUE THREAD

**Issue by Cmion** [sourcegraph/jetbrains#1154] opened 2024-03-21 13:16 UTC
### Cody Version

5.4.358

### IDE Information

WebStorm 2023.3.5
Build #WS-233.14808.24, built on March 13, 2024
Licensed to Simeon Akpanudo
Subscription is active until June 22, 2024.
Runtime version: 17.0.10+1-b1087.21 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  ide.intellij.laf.enable.animation=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.brandiico.jetbrains-nightfall-theme (2.0.1)
  Rider UI Theme Pack (0.14.11)
  com.mallowigi.idea (23.0.0)
  com.intellij.kubernetes (233.14475.2)
  com.sourcegraph.jetbrains (5.4.358)
  com.intellij.mermaid (0.0.20+IJ.232)
  zielu.gittoolbox (500.2.1+233)
  mdx.js (233.11799.172)
  ru.adelf.idea.dotenv (2024.1)

### Describe the bug

The Cody UI seems frozen, I cannot change AI model and when I post a question it keeps loading with no response, after which it causes my **IDE to crash**.

### Expected behavior

Cody should respond to my input, allow AI Model change and most importantly **NOT CRASH MY IDE**

### Additional context

Stacktrace:
```text
java.util.concurrent.CompletionException: java.lang.Exception: Failed to start Cody agent
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.getNow(CompletableFuture.java:2134)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$1(CodyAgentService.kt:129)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.Exception: Failed to start Cody agent
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:74)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 7 more
Caused by: java.io.IOException: Cannot run program "/Users/cmion/Library/Application Support/JetBrains/WebStorm2023.3/plugins/Sourcegraph/agent/agent-macos-arm64": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.sourcegraph.cody.agent.CodyAgent$Companion.startAgentProcess(CodyAgent.kt:163)
	at com.sourcegraph.cody.agent.CodyAgent$Companion.create(CodyAgent.kt:99)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:61)
	... 10 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 14 more

```

**Comment by mkondratek** [comment] 2024-04-17 15:41
hello @Cmion  👋 we are sorry you experience these troubles 

please try to update the plugin 🙏 

I am closing this one - not as a solved yet but as a duplicate of https://github.com/sourcegraph/jetbrains/issues/1328 - feel free to track the progress there

**Closed as completed by mkondratek** 2024-04-17 15:41 UTC
Labels: bug
