### ISSUE TITLE
Cody stops generating code after ~200 lines

### ISSUE THREAD

**Issue by AJKemps** [sourcegraph/jetbrains#153] opened 2023-12-01 21:39 UTC
Sourcegraph version: 5.2.2
Reported by: https://github.com/sourcegraph/accounts/issues/6938

Steps to reproduce:

Attempt to convert a file from one language to another by pasting the contents of a file into the Cody JetBrains extension.

https://hello.chorus.ai/listen?guid=a4ac08997ff74206b3902e0c7de35d35

Expected behavior:
Cody should be able to complete the file translation. If it stops early, we should explain why.

Actual behavior:
Cody just stops around 200-300 lines without explanation.

**Comment by chwarwick** [comment] 2023-12-01 22:42
I think this is likely related to the max prompt size due to a large amount of content being pasted in the chat window. 

This issue is likely not specific to the JetBrains extension.

**Comment by chwarwick** [comment] 2023-12-05 18:45
I think this is primarily due to the agent (vs code extension) logic to truncate user prompts at an estimated 1000 tokens.  Currently the prompt input is bound so users copy paste large chunks of code expecting them to be translated, however the prompt is then truncated to the first ~4000 characters when this completes it appears as if the response is terminated early.

**Comment by chwarwick** [comment] 2023-12-05 19:05
I think a reasonable solution here is to align the prompt input size with the max prompt that will used.

**Comment by pkukielka** [comment] 2023-12-21 15:31
> This issue is likely not specific to the JetBrains extension.

I can confirm that, I just checked in VS Code and behaviour is exactly the same.

**Comment by taylorsperry** [comment] 2024-01-09 00:53
> I think a reasonable solution here is to align the prompt input size with the max prompt that will used.

This seems like a good solution. Is there a way to do this dynamically, so that if the max prompt size changes, the prompt input size updates to match it? As far as UX, I noticed that instead of a counter that notifies the user 0/4000, 17/4000, 35/4000 etc as they type, Twitter is showing something like this ⬇️ WDYT, @danielmarquespt ?

![Image](https://github.com/sourcegraph/jetbrains/assets/43555476/9abb5a02-bf86-4a25-8800-24fbe2805034)

**Closed as not planned** 2024-06-03 22:07 UTC
Labels: bug, gtm-input, clients/jetbrains, Hide from cycles
