### ISSUE TITLE
bug: crash whilst using chat in pycharm

### ISSUE THREAD

**Issue by simonintech** [sourcegraph/jetbrains#248] opened 2024-01-05 11:34 UTC
### Installation Information

PyCharm 2023.3.1 (Community Edition)
Build #PC-233.11799.298, built on December 12, 2023
Runtime version: 17.0.9+7-b1087.7 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (5.2.15221)

### Describe the bug

Installed plugin version 5.2.15221

Opened chat window. Created a prompt in char window along the following lines -

"Outline high level functionality implemented within this repo"

executed prompt. chat window appeared to hang. eventually error dialog appeared.

![image](https://github.com/sourcegraph/jetbrains/assets/23657075/d023a423-5491-4fcd-92b3-707fda6caf3d)

### Expected behavior

Expected response from prompt

**Comment by taylorsperry** [comment] 2024-01-09 01:13
Thank you for reporting, @simoncwaterer! Marking as P0.

**Comment by pkukielka** [comment] 2024-02-14 12:57
I cannot reproduce on the newest versions which is not surprising as this code was completely rewritten.
I talked with @simoncwaterer and it only happened to him once as well.
It also was not reproduced by anyone else.
We decided that for now we can close it.

**Closed as completed by pkukielka** 2024-02-14 12:57 UTC
Labels: bug, gtm-input
