### ISSUE TITLE
Cody Ignore UI-level blocks

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/jetbrains#1494] opened 2024-05-13 04:10 UTC

**Comment by dominiccooney** [comment] 2024-05-13 04:11
@taylorsperry what's the priority on this one? Since Cody Ignore is new I guess adoption is 0 so... P1?

**Comment by taylorsperry** [comment] 2024-05-13 18:04
I'm not exactly sure what the issue is. Is this enabling telemetry to send an event when a user encounters a UI warning that "Cody is Limited" due to the admin enabling Cody Ignore?

**Comment by dominiccooney** [comment] 2024-05-14 04:58
Yes, that is it. We have zero Telemetry on these so as-is we won't know how often users are getting actions blocked by Cody Ignore.

**Comment by taylorsperry** [comment] 2024-05-14 13:47
Got it, thanks! @aramaraju is this a GA blocker? Marking as P1 for now.

**Comment by aramaraju** [comment] 2024-05-27 21:22
Good with a P1 👍

**Closed as completed** 2024-12-02 22:19 UTC
Labels: telemetry, clients/jetbrains, repo/jetbrains
