### ISSUE TITLE
bug: java.lang.IndexOutOfBoundsException: Wrong startOffset: 2017; documentLength: 1137

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/jetbrains#1605] opened 2024-05-23 08:38 UTC
### Cody Version

cody main 55275b76f0322729dcde8073741062562c613ba2, jetbrains main 33b46abc81059be8658a6aff57ad7efe02a5d6d3

### IDE Information

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 12
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

### Describe the bug

1. Open sourcegraph/jetbrains project
2. Open CodyToolWindowContent.kt
3. Click in `focusOnChat`. Alt up arrow twice to select the function.
4. Right click, Cody, Generate Unit Test
5. Flip back to CodyToolWindowContent.kt during generation a few times (it will fight with you and flip focus back), change the selection
6. When generation is done, *without accepting*, repeat from step 2.

### Expected behavior

Do not cause exceptions.

It is weird because I'm not clicking anywhere near "undo" here (AFAIK...)

### Additional context

Stacktrace:

```text
java.lang.IndexOutOfBoundsException: Wrong startOffset: 2017; documentLength: 1137
 at com.intellij.openapi.editor.impl.DocumentImpl.assertBounds(DocumentImpl.java:670)
 at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:606)
 at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:600)
 at com.sourcegraph.cody.edit.fixupActions.ReplaceUndoableAction.undo(ReplaceUndoableAction.kt:57)
 at com.sourcegraph.cody.edit.sessions.FixupSession.createDiffDocument$lambda$22(FixupSession.kt:399)
 at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$4(WriteCommandAction.java:362)
 at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:150)
 at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1015)
 at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$2(WriteCommandAction.java:148)
 at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
 at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:184)
 at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:157)
 at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:124)
 at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:362)
 at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:350)
 at com.sourcegraph.cody.edit.sessions.FixupSession.createDiffDocument(FixupSession.kt:398)
 at com.sourcegraph.cody.edit.EditShowDiffAction.getDiffRequestChain(EditShowDiffAction.kt:29)
 at com.intellij.diff.actions.BaseShowDiffAction.actionPerformed(BaseShowDiffAction.java:56)
 at com.sourcegraph.cody.edit.widget.LensAction.triggerAction(LensAction.kt:89)
 at com.sourcegraph.cody.edit.widget.LensAction.onClick(LensAction.kt:73)
 at com.sourcegraph.cody.edit.widget.LensWidgetGroup.handleMouseClick(LensWidgetGroup.kt:256)
 at com.sourcegraph.cody.edit.widget.LensWidgetGroup.access$handleMouseClick(LensWidgetGroup.kt:48)
 at com.sourcegraph.cody.edit.widget.LensWidgetGroup$mouseClickListener$1.mouseClicked(LensWidgetGroup.kt:63)
 at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseClickedCommand(EditorImpl.java:3923)
 at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:3842)
 at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
 at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
 at java.desktop/java.awt.Component.processEvent(Component.java:6419)
 at java.desktop/java.awt.Container.processEvent(Container.java:2263)
 at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
 at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
 at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
 at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
 at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
 at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
 at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
 at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
 at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
 at java.base/java.security.AccessController.doPrivileged(Native Method)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
 at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
 at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
 at java.base/java.security.AccessController.doPrivileged(Native Method)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
 at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
 at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
 at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
 at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
 at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
 at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
 at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
 at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
 at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
 at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
 at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
 
```

**Comment by mkondratek** [comment] 2024-05-29 22:02
I cannot reproduce it on 6.0.0. We applied a lot of fixes to doc sync & ranges. Let's close it.

**Closed as completed by mkondratek** 2024-05-29 22:02 UTC
Labels: bug
