### ISSUE TITLE
bug: com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.source...

### ISSUE THREAD

**Issue by ajvengo** [sourcegraph/jetbrains#1288] opened 2024-04-05 11:03 UTC
### Cody Version

5.5.2

### IDE Information

GoLand 2024.1
Build #GO-241.14494.238, built on March 28, 2024
Licensed to Booking.com B.V.

Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.intellij.lang.puppet (241.14494.150)
  com.intellij.tasks (241.14494.150)
  String Manipulation (9.12.0)
  com.intellij.mermaid (0.0.21+IJ.232)
  com.jetbrains.space (241.14494.150)
  org.intellij.plugins.postcss (241.14494.155)
  com.intellij.kubernetes (241.14494.150)
  com.sourcegraph.jetbrains (5.5.2)
  tslint (241.14494.155)
  intellij.prettierJS (241.14494.155)
  com.fapiko.jetbrains.plugins.better_direnv (1.2.2)

### Describe the bug

Warning about deprecated method `ActionUpdateThread.OLD_EDT`

### Expected behavior

No deprecation warnings

### Additional context

Stacktrace:
```text
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.sourcegraph.website.OpenRevisionAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.sourcegraph.jetbrains]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

```

**Comment by odisseus** [comment] 2024-04-17 22:14
Duplicate of #1327.

**Closed as not planned** 2024-04-17 22:15 UTC
Labels: bug
