### ISSUE TITLE
bug: com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service com.sourcegraph.cody.agent.CodyAgentServi...

### ISSUE THREAD

**Issue by anupam1187** [sourcegraph/jetbrains#2490] opened 2024-10-20 10:23 UTC
### IDE Information

IntelliJ IDEA 2023.2.8 (Ultimate Edition)
Build #IU-232.10335.12, built on September 5, 2024
Licensed to Anupam Das
Subscription is active until September 5, 2025.
For educational use only.
Runtime version: 17.0.12+7-b1000.54 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3048M
Cores: 6
Non-Bundled Plugins:
    ink.organics.pojo2json (2.0.6)
    com.sourcegraph.jetbrains (7.0.13)
    zielu.gittoolbox (500.2.12+223)
    com.intellij.bigdatatools.core (232.10335.12)
    com.intellij.bigdatatools.kafka (232.10335.12)

Kotlin: 232-1.9.0-IJ10335.12

### Bug Description

ALWAYS SHOWING THIS ERROR

### Additional context

Stacktrace:
```text
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service com.sourcegraph.cody.agent.CodyAgentService because container is already disposed (container=Project(name=APON BAZAR, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\BS540\Desktop\APON BAZAR) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkThatCreatingOfLightServiceIsAllowed(ComponentManagerImpl.kt:752)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:732)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:688)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.getInstance(CodyAgentService.kt:227)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$2(CodyAgentService.kt:191)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by mkondratek** [comment] 2024-11-07 22:07
Hello 👋 thank you for the report. Sorry for the inconvenience 🙇 

I am working on fixing this one, here is my PR: https://github.com/sourcegraph/jetbrains/pull/2597

Also, this report is a duplicate of https://github.com/sourcegraph/jetbrains/issues/2517 so I am closing it 📕

**Closed as not planned by mkondratek** 2024-11-07 22:07 UTC
Labels: bug, repo/jetbrains
