### ISSUE TITLE
Editing remote file causes cody to crash.

### ISSUE THREAD

**Issue by abdikafar** [sourcegraph/jetbrains#2906] opened 2024-12-30 16:00 UTC
### IDE Information

PhpStorm 2023.2.4
Build #PS-232.10227.13, built on November 18, 2023
Licensed to Abdikafar Abdirahman
You have a perpetual fallback license for this version.
Subscription expired on September 17, 2024.
Runtime version: 17.0.9+7-b1000.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    editor.focus.mode.color.light=657778
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.animate.toolwindows=true
    run.processes.with.pty=TRUE
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=657778

Non-Bundled Plugins:
    com.fernandojimenez.mattecarbon.theme (3.0.0)
    com.intellij.ideolog (222.1.0.0)
    ru.adelf.idea.dotenv (2023.2)
    nl.deschepers.laraveltinker (2.6.1)
    de.beyondco.tinkerwell.tinkerwell (2.6.1)
    com.github.copilot (1.5.0.5148)
    com.chrisrm.idea.MaterialThemeUI (8.12.6)
    com.github.inxilpro.intellijalpine (v0.4.2)
    com.sourcegraph.jetbrains (7.4.3)
    com.mallowigi (93.1.0)

### Bug Description

when ever i try to edit a remote file my cody ai assistant crashes.

### Additional context

Stacktrace:
```text
java.nio.file.InvalidPathException: Illegal char <<> at index 0: <d35ea697-6a02-4b20-91e2-2a69f76959a0>/mobileapi/application/controllers/Appservice.php
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:177)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at com.sourcegraph.cody.agent.protocol_extensions.ProtocolTextDocumentExt.uriFor(ProtocolTextDocument.kt:174)
	at com.sourcegraph.cody.agent.protocol_extensions.ProtocolTextDocumentExt.fromVirtualEditorFile(ProtocolTextDocument.kt:156)
	at com.sourcegraph.cody.agent.protocol_extensions.ProtocolTextDocumentExt.fromEditor(ProtocolTextDocument.kt:147)
	at com.sourcegraph.cody.listeners.CodyFocusChangeListener.focusGained(CodyFocusChangeListener.kt:19)
	at com.intellij.openapi.editor.ex.FocusChangeListener.focusGained(FocusChangeListener.java:18)
	at jdk.internal.reflect.GeneratedMethodAccessor334.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:118)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:83)
	at jdk.proxy2/jdk.proxy2.$Proxy104.focusGained(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorImpl.fireFocusGained(EditorImpl.java:1354)
	at com.intellij.openapi.editor.impl.EditorImpl.focusGained(EditorImpl.java:583)
	at java.desktop/java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:227)
	at java.desktop/java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:227)
	at java.desktop/java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:227)
	at java.desktop/java.awt.Component.processFocusEvent(Component.java:6546)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1064)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:688)
	at com.intellij.ide.IdeKeyboardFocusManager.access$dispatchEvent$s1569605750(IdeKeyboardFocusManager.kt:18)
	at com.intellij.ide.IdeKeyboardFocusManager$dispatchEvent$1.invoke(IdeKeyboardFocusManager.kt:25)
	at com.intellij.ide.IdeKeyboardFocusManager$dispatchEvent$1.invoke(IdeKeyboardFocusManager.kt:25)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.kt:25)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4904)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/sun.awt.SunToolkit$1.run(SunToolkit.java:524)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.Application...

**Comment by PriNova** [comment] 2024-12-31 10:12
Hey @abdikafar 

Thank you for reporting this issue.
Could you please describe in detail what you mean with "editing remote files"? Where are those files stored and how do try to access them?

Thank you

**Comment by PriNova** [comment] 2024-12-31 10:15
Duplicate of #2696

**Closed as not planned** 2024-12-31 10:17 UTC
Labels: bug, repo/jetbrains
