### ISSUE TITLE
Cody showing nothing and always loading

### ISSUE THREAD

**Issue by rosca-cristian** [sourcegraph/jetbrains#2470] opened 2024-10-17 06:32 UTC
### IDE Information

Webstorm 2024.2.3

### Bug Description

I tried installing and uninstalling, enabling and disabling and logging out and logging in, but nothing happens; it's still stuck on this screen.

![image](https://github.com/user-attachments/assets/99556fb9-9940-4b25-b8e2-3ead722fa520)

**Comment by L4rue** [comment] 2024-10-17 06:42
Same to you. I have to rollback to 7.0.6 to fix

**Comment by fredferrao** [comment] 2024-10-17 13:12
Same here on InteliJJ Ultimate, version 7.0.13 just doesn't work, I’ve already tried reinstalling the plugin, invalidating the cache, restarting Cody several times, but it doesn’t work.

I found it strange right after the update when IntelliJ informed me that Full Line Code Complete no longer had a conflict and could be used.

Had to manually downgrade to 7.0.6.

**Comment by ccasselman** [comment] 2024-10-17 17:40
Same.  It seems every release is untested and unverified.

**Comment by jafin** [comment] 2024-10-19 00:51
possible duplicate of #2447

**Comment by Nopik** [comment] 2024-10-21 12:49
> Same. It seems every release is untested and unverified.

Indeed. It is astonishing that a totally broken upgrade which makes plugin to not work at all stays not addressed for so long.

**Comment by kalanchan** [comment] 2024-10-21 23:12
sorry for the inconvenience everyone, we're working on releasing another stable version as soon as we can.

**Comment by dominiccooney** [comment] 2024-10-22 08:09
It would be great to get an `idea.log` (Help, Show Log in ...) when this happens. Even better if you can invoke the Open Cody Settings action and set it to the following and restart.

```
{
  "cody.debug.verbose": true
}
```

**Comment by Nopik** [comment] 2024-10-22 09:17
Here it is. I was on older Cody, so I added the verbose setting there. Upgraded plugin. Deleted all `idea.log` files. Restarted IDE. Cody panel was empty, not even 3 color dot spinner. I clicked 'restart cody', so 3 dots appeared. I played with other settings I've seen - the 'restart' disappeared, but I think I disabled the autocomplete. Here is the log afterwards.

[idea.log.zip](https://github.com/user-attachments/files/17473434/idea.log.zip)

**Comment by Nopik** [comment] 2024-10-22 09:20
As you can see in the log, lots of exceptions like this:

```
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent - Uncaught exception: SyntaxError: "undefined" is not valid JSON
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at JSON.parse (<anonymous>)
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at LocalStorageDB.get (/Users/nopik/Library/Application Support/JetBrains/IntelliJIdea2024.2/plugins/Sourcegraph/agent/index.js:132840:28)
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at _AgentGlobalState.get (/Users/nopik/Library/Application Support/JetBrains/IntelliJIdea2024.2/plugins/Sourcegraph/agent/index.js:132796:26)
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at LocalStorage.get (/Users/nopik/Library/Application Support/JetBrains/IntelliJIdea2024.2/plugins/Sourcegraph/agent/index.js:96677:29)
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at LocalStorage.getClientState (/Users/nopik/Library/Application Support/JetBrains/IntelliJIdea2024.2/plugins/Sourcegraph/agent/index.js:96493:29)
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at /Users/nopik/Library/Application Support/JetBrains/IntelliJIdea2024.2/plugins/Sourcegraph/agent/index.js:96500:34
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at Object.<anonymous> (/Users/nopik/Library/Application Support/JetBrains/IntelliJIdea2024.2/plugins/Sourcegraph/agent/index.js:27465:34)
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at Generator.next (<anonymous>)
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at /Users/nopik/Library/Application Support/JetBrains/IntelliJIdea2024.2/plugins/Sourcegraph/agent/index.js:27504:71
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at new Promise (<anonymous>)
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at __awaiter3 (/Users/nopik/Library/Application Support/JetBrains/IntelliJIdea2024.2/plugins/Sourcegraph/agent/index.js:27486:14)
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at /Users/nopik/Library/Application Support/JetBrains/IntelliJIdea2024.2/plugins/Sourcegraph/agent/index.js:27464:40
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at AsyncSerialScheduler.<anonymous> (/Users/nopik/Library/Application Support/JetBrains/IntelliJIdea2024.2/plugins/Sourcegraph/agent/index.js:26819:17)
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at Generator.next (<anonymous>)
2024-10-22 11:14:33,720 [  56279]   WARN - #com.sourcegraph.cody.agent.CodyAgent -     at fulfilled (/Users/nopik/Library/Application Support/JetBrains/IntelliJIdea2024.2/plugins/Sourcegraph/agent/index.js:26784:28)
2
```

**Comment by Nopik** [comment] 2024-10-22 09:21
@dominiccooney @kalanchan ^

**Comment by jdorfman** [comment] 2024-10-25 15:54
Hey all! 7.0.18 is already waiting for JetBrains verification in Marketplace, so it should be out around Monday-Tue. If you can't wait, you can try it on our nightly build.

cc: @jafin @fredferrao @Nopik @ccasselman

**Comment by Nopik** [comment] 2024-10-25 16:00
Thanks, 7.0.18-nightly works for me.

**Comment by ccasselman** [comment] 2024-10-25 17:09
How do we install from the nightly build - It doesn't work for the 7.0.18 or the 7.0.18-nightly zips? @jdorfman

**Comment by Nopik** [comment] 2024-10-25 17:12
@ccasselman download zip from https://plugins.jetbrains.com/plugin/9682-sourcegraph/versions/nightly and then in your IDE choose 'Install Plugin from Disk' and point it to the zip
<img width="837" alt="image" src="https://github.com/user-attachments/assets/17df5bc8-9036-4a8c-88fa-c36306a50dbb">

**Comment by jafin** [comment] 2024-10-26 22:58
@jdorfman 7.0.18 nightly fixed it here (Rider). Thank you. 👏🏻

**Comment by jdorfman** [comment] 2024-10-27 18:42
@jafin great to hear, thanks for following up. You are welcome. :)

**Closed as completed** 2024-10-28 04:14 UTC
Labels: bug, repo/jetbrains
