### ISSUE TITLE
Ask Cody to fix inspection

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/jetbrains#117] opened 2023-11-13 13:36 UTC
As a user, I want Cody to apply a fix to errors detected in my project.

* A fix can be triggered by opening a Code Inspection and selecting a new option to "Ask Cody to Fix"
* Cody runs an "Edit" command in the background, with instructions to fix the error.
* In an open project file, Cody automatically applies a code fix to the selected code.
* Users can accept, edit and retry, see a diff view of the vix, or undo the fix.
* Executing the "fix" command fires a telemetry event aligned with the current VSC implementation.

  <img src="https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/5efb7518-2135-4f43-b3af-b6c622e28b06/638176b6-c937-460d-afda-aeabde77c1dc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy81ZWZiNzUxOC0yMTM1LTRmNDMtYjNhZi1iNmM2MjJlMjhiMDYvNjM4MTc2YjYtYzkzNy00NjBkLWFmZGEtYWVhYmRlNzdjMWRjIiwiaWF0IjoxNzE4NzE3OTQ4LCJleHAiOjMzMjg5Mjc3OTQ4fQ.bR52ycIfoEMIsIraZFF0XXAnNHNHj5Q61oBvXP8IstE " alt="Screenshot 2024-06-18 at 7.38.51 AM.png" width="527" height="564" />

**Comment by taylorsperry** [comment] 2024-05-09 14:18
Closing as a dupe of https://github.com/sourcegraph/jetbrains/issues/103

**Closed as completed** 2024-08-05 16:01 UTC
Labels: clients/jetbrains
